### ISSUE TITLE
Buttons on the dataset page not showing

### ISSUE THREAD

**Issue by andreskytt** [okestonia/jkan#104]
The buttons "Alusta arutelu" and "Muuda Githubis" do not show up on the dataset page (e.g. https://opendata.riik.ee/andmehulgad/Ametlike-teadaannete/) on Chrome on OS X (Safari on OS X is fine)

**Comment by keeganmcbride** [comment]
@andreskytt can you check if bootstrap update fixed this?

**Comment by andreskytt** [comment]
Confirmed to be working
