### ISSUE TITLE
Fix the image width

### ISSUE THREAD

**Issue by andreskytt** [okestonia/jkan#117]
In https://opendata.riik.ee/en/blogi/what-impact-border-trading-local-traffic/, the main diagram (snippet <img src="https://raw.githubusercontent.com/okestonia/Data-Viz-Protos/master/piirikaubandus/traffic_violation.png">) lacks a width attribute, this makes the image exceed screen size on many devices

**Comment by keeganmcbride** [comment]
fixed.
