### ISSUE TITLE
Add Facebook icon linked to openESTdata group 

### ISSUE THREAD

**Issue by infokujur** [okestonia/jkan#118]
https://www.facebook.com/groups/1792458637715167

Next to "Lisainfo" on the menu bar.

**Comment by keeganmcbride** [comment]
Are there any other social media icons we should add?

**Comment by keeganmcbride** [comment]
Are there any other social media icons we should add?

**Comment by infokujur** [comment]
Twitter also: https://twitter.com/openESTdata

**Comment by otuxe** [comment]
It is absolutely fine! Great idea!

**Comment by keeganmcbride** [comment]
Facebook and GitHub to header and footer + twitter to footer also
