### ISSUE TITLE
Add field for organizations - Twitter handle

### ISSUE THREAD

**Issue by infokujur** [okestonia/jkan#123]
For example Riigikantselei @EstonianGovt

**Comment by keeganmcbride** [comment]
Assign to maarja leena once added field.

**Comment by infokujur** [comment]
@keeganmcbride - So there is a field now? How I should contrib with content? Should I create csv what You can use for updating?

**Comment by keeganmcbride** [comment]
This is done, adding organizations twitter handles is a seperate issue, but the field now exists.
