### ISSUE TITLE
Validated URLs

### ISSUE THREAD

**Issue by keeganmcbride** [okestonia/jkan#126]
We now are checking URLs for validity every night (link returns status 200), now we need to decide what to do with this and how to display. Currently, data is available here: https://opendata.riik.ee/validated.json . Reponse types = 200,403,404, timedout

**Comment by keeganmcbride** [comment]
UTF-8 for organization names broken @andreskytt

**Comment by infokujur** [comment]
Can we update opendata-issue-tracker with new issues - containing info about the problem and assigning them to the contact (and if no github contact, then automatic email)?

**Comment by keeganmcbride** [comment]
@andreskytt this no longer works due to error handling issues.

**Comment by keeganmcbride** [comment]
@andreskytt to fix this sprint.
