### ISSUE TITLE
Update text files

### ISSUE THREAD

**Issue by infokujur** [okestonia/jkan#140]
#86 

@maarjatoots will update info here.

**Comment by keeganmcbride** [comment]
Send technical info to @maarjatoots or @infokujur so that they can write this.

**Comment by infokujur** [comment]
[opendata LISA toim KP 05022019.docx](https://github.com/okestonia/jkan/files/2835362/opendata.LISA.toim.KP.05022019.docx)
Adding last blogpost

**Comment by infokujur** [comment]
[open data ET toim 23012019.docx](https://github.com/okestonia/jkan/files/2835364/open.data.ET.toim.23012019.docx)
All EST files

**Comment by infokujur** [comment]
[open data ET-EN tlk 17012019.docx](https://github.com/okestonia/jkan/files/2835371/open.data.ET-EN.tlk.17012019.docx)
[open data EN toim 18012019.docx](https://github.com/okestonia/jkan/files/2835372/open.data.EN.toim.18012019.docx)
EST-ENG translations

**Comment by infokujur** [comment]
[open data ET-EN tlk DATASETS 17012019 NEW.docx](https://github.com/okestonia/jkan/files/2835374/open.data.ET-EN.tlk.DATASETS.17012019.NEW.docx)
[open data ET DATASETS 17012019.docx](https://github.com/okestonia/jkan/files/2835375/open.data.ET.DATASETS.17012019.docx)
Datasets

**Comment by infokujur** [comment]
[open data EN texts FINAL 1202019.docx](https://github.com/okestonia/jkan/files/2859413/open.data.EN.texts.FINAL.1202019.docx)
[open data EN datasets FINAL 1202019.docx](https://github.com/okestonia/jkan/files/2859414/open.data.EN.datasets.FINAL.1202019.docx)
[open data ET datasets FINAL 1202019.docx](https://github.com/okestonia/jkan/files/2859415/open.data.ET.datasets.FINAL.1202019.docx)
[open data ET texts FINAL 1202019 puuduvad asjad.docx](https://github.com/okestonia/jkan/files/2859416/open.data.ET.texts.FINAL.1202019.puuduvad.asjad.docx)

**Comment by keeganmcbride** [comment]
@annegretepeek Can you fix the text in your blog posts based on the corrections here?
