### ISSUE TITLE
public sector expenses for software and hardware

### ISSUE THREAD

**Issue by edmundlaugasson** [okestonia/jkan#149]
It is strange that Estonia cannot collect information in Estonian language anymore and we need to speak English even it is not the official language and hopefully never will be.

Reminding the article [Riigi andmed on nüüd kergesti kättesaadavad](http://www.ituudised.ee/uudised/2018/12/03/riigi-andmed-on-nuud-kergesti-kattesaadavad) ([unofficial translation](https://translate.google.com/translate?hl=en&sl=et&tl=en&u=http%3A%2F%2Fwww.ituudised.ee%2Fuudised%2F2018%2F12%2F03%2Friigi-andmed-on-nuud-kergesti-kattesaadavad)) from December 3, 2018 then we have to admit that public data is not yet easily available as it claims in referenced article.

Next articles on January 14, 2019:
* [Palju Sepp ja Ratas parteikassasse viisid? E-riik Eesti on avaandmete osas teistest maadest palju kehvem](https://digi.geenius.ee/rubriik/uudis/palju-sepp-ja-ratas-parteikassasse-viisid-e-riik-eesti-on-avaandmete-osas-teistest-maadest-palju-kehvem/)  ([unofficial translation](https://translate.google.com/translate?hl=en&sl=et&tl=en&u=https%3A%2F%2Fdigi.geenius.ee%2Frubriik%2Fuudis%2Fpalju-sepp-ja-ratas-parteikassasse-viisid-e-riik-eesti-on-avaandmete-osas-teistest-maadest-palju-kehvem%2F))
* [E-riigi andmejuht: me ootame konkreetseid ettepanekuid, milliseid avaandmeid tahetakse](https://digi.geenius.ee/rubriik/uudis/e-riigi-andmejuht-me-ootame-konkreetseid-ettepanekuid-milliseid-avaandmeid-tahetakse/)  ([unofficial translation](https://translate.google.com/translate?hl=en&sl=et&tl=en&u=https%3A%2F%2Fdigi.geenius.ee%2Frubriik%2Fuudis%2Fe-riigi-andmejuht-me-ootame-konkreetseid-ettepanekuid-milliseid-avaandmeid-tahetakse%2F&sandbox=1))

... came already as surprises which shows [that the location close to here](https://github.com/okestonia/opendata-issue-tracker) has not been acknowledged.

**Proposal**
Estonia as an IT country should have an overview about expenses for software and hardware. It would be part of open data, which is difficult to retrieve and plan related developments, therefore related research is complex (not to say impossible) to plan.

**What to show?**
* software procurements
  * closed source
  * open-source
* number of workplaces with computers
* number of servers
* used software - if many then all should be detected
  * operating system
    * workplaces
    * servers
  * office suite (e.g. MS Office, LibreOffice etc.)
  * file manager
  * web browser
  * e-mail client or mention that checking over web
  * other software used to work
* virtualization software
  * platform virtualization (e.g. VMware, Virtualbox, KVM, etc.)
  * using conteiners (e.g. docker, LXC, etc.)
* should be possible to filter with certain time period
  * spent money per workplace, server
  * one workplace cost and with which software
* an overview of main hardware:
  * processors (CPU - microprocessor, QPU - quantum processor)
  * operating memory (RAM)
  * hard disks (SSD - non-spinning disk, HDD - spinning disk)
    * used file systems
* also Internet connection speed should be determined - e.g. once a year and if e.g. external IP etc changes then system detects that there is new ISP and measures speed automatically again
* all the information requested here should be renewed at least once a year

**Output environment?**
Some ideas:
* https://www.haridussilm.ee/ - here would be good to show per educational institution and then all information about educational institution would be in one place where all this is collected. As there are often wanted to offer solutions for educational institutions and currently such a web site exist already with lots of data about educational institutions then it would be an admirable opportunity to add ICT layers there.
* all public sector information (including educational institutions one)  kogu avaliku sektori infot (sh haridusasutused) could be displayed (with more detail as until today, at least in the range of current requests) e.g.:
  * http://riigiraha.fin.ee/
  * http://meieraha.ee/
* information should be possible to filter by educational institution, ministry - e.g. based on same categories like eesti.ee has done - https://www.eesti.ee/est/kontaktid (Estonian, more complete), https://www.eesti.ee/eng/contacts (English)
* information should be possible to see per whole country and per [administrative unit](https://www.riigiteataja.ee/akt/13193609?leiaKehtiv) (per county, parish, city) and also per one person

**Optional solution for data collection**
Whole point is to collect all requested data automatically without human intervention. All this could be achieved just by installing a small program onto public sector computers and then there would be possible to collect data automatically and periodically.

One suitable software could be OCS Inventory - https://www.ocsinventory-ng.org/ - allows together with GLPI get an overview of whole public ICT sector assets - https://glpi-project.org/
OCS Inventory free alternatives - https://alternativeto.net/software/ocsinventory-ng-org/?license=opensource

Another idea is to create a separate application like here as been already created - https://opendata.riik.ee/rakendused/ - this might be possibly easier than interfere existing environments.

**Benefits (what to do with collected data)**
it would give:
* an opportunity for all: state, local authority, organization decisionmakers have practically real-time information of whole public sector ICT assets and software - this could be raisin, why there should be wanted that state has such overview. There should be no objection  if state would like to have an overview of its assets. Also taxpayer would like to have that as using their money all this has been bought finally.
* government could ensure as homogeneous ICT level as possible in whole state
* there would be an overview where is enough powerful hardware where could be used e.g. platform virtualization as  there are and will be in future created learning objects, applications for business environments as virtual appliances and to use them, we need platform virtualization
* having an operative overview there can be also operative and appropriate decisions made
* scientists, enterprises etc. have an opportunity to do research without bothering anyone and saving lots of time, etc. resources which are 
* teadlastel, ettevõtetel jt on võimalus omakorda teha uuringuid ilma, et peaks kedagi tülitama ja säästes samal ajal aega jm ressursse, what is already lacking and plan products, services etc. This in turn could help to revive economy.

**What has been done so far?**
* in May 2015 communicated with Ministry of Education and Research (Ingrid Jaggo) as the manager of haridussilm.ee - did not come with the proposed idea - claimed that ICT-related data in [EHIS](http://www.ehis.ee/) are partically inserted and incorrect. This was the idea, that not to take incorrect data from EHIS but collect them automatically using appropriate software.
* in September 2016 there has been communicated with [EENet](http://www.eenet.ee/EENet/EENet_en) (Indrek Rokk) - currently lack of resources to start and manage all this. Also was the opinion that why there is needed to reveal ICT-related information.....
* current overview is chaotic, e.g.
  * https://www.err.ee/597259/eesti-riik-maksab-microsoftile-miljoneid-eurosid-aastas - The Estonian state pays millions of euros a year to Microsoft ([unofficial translation](https://translate.google.com/translate?hl=en&sl=et&tl=en&u=https%3A%2F%2Fwww.err.ee%2F597259%2Feesti-riik-maksab-microsoftile-miljoneid-eurosid-aastas))
  * https://wiki.fsfe.org/Activities/EUMicrosoftContracts#Estonia
  * https://riigihanked.riik.ee/ and search in Estonian _tarkvara (software)_, _litsents (licence)_, _Microsoft_ etc.

**What others do?**
There is an intriguing project in Europe - https://www.investigate-europe.eu/ - basically they investigate public money waste in Europe.

**Comment by edmundlaugasson** [comment]
https://github.com/okestonia/opendata-issue-tracker/issues/149 - same in Estonian

**Comment by infokujur** [comment]
Andmetega seotu hoiame siin: https://github.com/okestonia/opendata-issue-tracker/issues/149
Sulgen selle  kui dublikaadi. Kas siin on infot, mida opendata-issue-tracker -is pole? Kui nii, siis palun lisa see uute issudena.
