### ISSUE TITLE
opendata-issue-tracker vs jkan issues for datasets discussion

### ISSUE THREAD

**Issue by tormi** [okestonia/jkan#160]
https://opendata.riik.ee/andmehulgad/kinnisvararegister/ (or any other dataset) > `Alusta arutelu`* links to JKAN issue tracker instead of `opendata-issue-tracker`. Is this some mistake or intentional? Should we move discussions about datasets from `opendata-issue-tracker` to `jkan`?

*- https://github.com/okestonia/jkan/blob/5e5eb91afddaf1742db3618cff785c8b5592144d/_layouts/dataset.html#L160

**Comment by keeganmcbride** [comment]
This was intentional, but @infokujur  can clarify.

**Comment by infokujur** [comment]
Thank You for pointing that out! We discussed it with the team and we will move all the dataset discussions to opendata-issue-tracker.
The difference is the grooming process and general target group between these places.
