### ISSUE TITLE
Juhendid tuleb teha lihtsamaks/selgemaks

### ISSUE THREAD

**Issue by otuxe** [okestonia/jkan#185]
Kas oleks võimalik teha seda juhendeid teha lihtsamaks/selgemaks  ? Juhendid https://opendata.riik.ee/juhend/ ja https://github.com/okestonia/jkan/blob/master/_data/schemas/default.yml. Hetkel puuduvad default.yml ei sisalda kõik süsteemis olevaid parameetrite kirjeldusi ning neid peab otsima veebi koodist.
Kasutusjuhendis https://github.com/okestonia/jkan/blob/master/_data/schemas/default.yml on kirjeldamata järgmiste väljade väärtused, mis teevad keerukaks algajal avaandmete kirjeldamise :
category : a la transport (süsteemi ülese kategooriate kirjeldus)
license: nt 'http://creativecommons.org/licenses/by-sa/3.0/' . (tavainimene ei mõtle seda välja)
update_freq: 'http://purl.org/linked-data/sdmx/2009/code#freq-D': ühepäeva uuendamise intervall (tavainimene ei mõtle seda välja)
Kas kuskil oleks võimalik saada juhend, mis algajal teeks kõik puust ja punaseks ette ? Kõik andmete lisajad ei pruugi nii IT teadlikud olla.

**Comment by andreskytt** [comment]
Ma vajan siin copy kirjutamisel abi

**Comment by infokujur** [comment]
@andreskytt - palun pane sammud järjest kirja ja siis ma organiseerin ilusa jutu ümber.

**Comment by infokujur** [comment]
Samm 1 - Githubi kasutaja loomine https://github.com/join

**Comment by keeganmcbride** [comment]
@jamesherne wrote a new version.
