### ISSUE TITLE
Usage of ariregistri_kood in Teabevaldajad, Andmehulgad, Rakendused

### ISSUE THREAD

**Issue by ToomasMolder** [okestonia/jkan#194]
Problem: current solution allows data owners (contributors) to choose filenames and organisation names loosely, in different formats (using full name, using acronym, using unknown format, using name with spelling errors etc). This creates a mess, duplications etc. It requires additional manual check and probably also changes in original data files by administrator to keep data files and structure consistent.

Suggestion to add organization code (named as 'ariregistri_kood' or smth else) matching with http://avaandmed.rik.ee/andmed/ARIREGISTER/, field 'ariregistri_kood' into data files under /_organizations/, /_datasets/ (and /_datasetsen/), /_applications/.

Suggestion to rename data files to use 'ariregistri_kood' as mandatory part of it. 

Option to synchronize organisation name (field 'title' under /_organizations/, field 'organization' under /_datasets/, probably also field 'developed_by' under /_applications/) periodically to match with official data (field 'nimi').

Option to link directly into organisation current data (field 'teabesysteemi_link') and check status of organisation (field 'ettevotja_staatus') and raise alarm, start with issue when organisation has status other than 'R' (Registrisse kantud).

Update /juhend.md according to data fields and file name conventions.

**Comment by keeganmcbride** [comment]
Discussed internally, not in scope.
