### ISSUE TITLE
Usage of different languages in Teabevaldajad, Andmehulgad, Rakendused

### ISSUE THREAD

**Issue by ToomasMolder** [okestonia/jkan#195]
Problem: current solution collects information from data owners (contributors) mainly in Estonian. It is not understandable, where and how and when to fill the same in some other language (sample, in English). Content of Portal is not understandable for foreign language speakers, it does not open data from Estonia to the World enough.

Some contributors are ready to fulfill the organization, dataset and application data files also in other language.

Suggestion to add into structure of data files also markup of language and option to fill it.
It is possible to generate content of Portal in different languages then.
When field is not fulfilled with (another) language, then use the original.

Update /juhend.md according to data fields and translation conventions.

**Comment by keeganmcbride** [comment]
Hi Toomas,

Translation into English is something inscope and a fix is in progress, this will be included in the next sprint and then instructions will be added to the juhend page for this.

**Comment by keeganmcbride** [comment]
https://github.com/okestonia/jkan/pull/199 

Applications + Organizations translated through schema modification.

**Comment by ToomasMolder** [comment]
Had in mind, that the CONTENT of datasets, publishers and applications, provided to the portal by their respective owners are currently asked to be filled only in estonian and other languages not supported.

Just sample: being in english-language template https://opendata.riik.ee/en/datasets/ there are links to datasets, sample https://opendata.riik.ee/andmehulgad/x-road_v6_opendata_et/ (https://github.com/okestonia/jkan/edit/master/_datasets/x-road_v6_opendata_et.md).
The fields of dataset, like 'title', 'notes', 'resources/name', 'organization' are currently instructed to be filled only in estonian. Therefor the overall index https://opendata.riik.ee/en/datasets/  looks weird - template of page is in english but content is in estonian.
