### ISSUE TITLE
Menus KKK, Kontaktid and Meist under Lisainfo seems to present the same in different formats

### ISSUE THREAD

**Issue by ToomasMolder** [okestonia/jkan#197]
Menus 'KKK', 'Kontaktid' and 'Meist' under 'Lisainfo' seems to present the same in different formats.

It is possible to get rid of at least one of them, most probably 'Meist' might be forgotten because the same is covered already under 'KKK' and 'Kontaktid'.

If yes, then the same is true for english-language as well.

**Comment by keeganmcbride** [comment]
Ping @otuxe @infokujur

**Comment by keeganmcbride** [comment]
Will remove Meist section

**Comment by keeganmcbride** [comment]
@infokujur to talk with Piret about next step

**Comment by infokujur** [comment]
MVP approach to make it more clear.

1) Blog posts and and othe content under lisainfo needs to labeled with:
Artikkel/Article
Uudis/News
Juhend/Guide
Töödokument/Working paper
See more: https://github.com/okestonia/jkan/projects/4

2) And shorted accordingly:
Main menu:
- Blogi - Blog containing Artikkel/Article; Uudis/News type
- Lisainfo submenu
-- Juhendid/Guides containing Juhend/Guide type
-- Töödokumendid/Workin papers Töödokument/Working paper type
-- KKK/FAQ
-- Kontaktid/Contact information

3) Followed content needs to be labelled accordingly:
- Metaandmed/Metadata > Juhend/Guide type
- Avaandmete roheline raamat/Green Paper > Juhend/Guide type
- Avaandmete poliitika koordineerimine > Juhend/Guide type
- Avaandmete lisamise ja uuendamise juhend > Juhend/Guide type

@keeganmcbride can You look at this above. If needed please open separate issues.

Meist will be merged in KKK. @infokujur will do. https://github.com/okestonia/jkan/issues/360

**Comment by infokujur** [comment]
@keeganmcbride - Did You have any look at this?

**Comment by infokujur** [comment]
@maarjatoots will move on with this one. As She worked through all the reports, She has perfect idea how this material should be structured.

**Comment by maarjatoots** [comment]
Proposing a new structure for the "Lisainfo/More info" submenu. Only level 1 headings would show up in the menu, level 2 headings below just indicate content that could be moved under (or added to) the respective section. 

**EE:**
1. Avaandmete poliitika
1.1 Avaliku teabe seadus 
(_brief intro + link to Riigi Teataja_)
1.2 Avaandmete roheline raamat 
(_brief intro + link to file on MKM’s website_) 
1.3 Avaandmete poliitika koordineerimine
2. Andmete avaldamise juhendid
2.1 Andmete avaldamine portaalis
2.2 Teiseste andmete avaldamine
2.3 Litsentsid 
(_translation of CC 4.0 here_)
2.4 Metaandmed
3. Sündmused ja infomaterjalid
4. KKK
5. Kontaktid

**EN:**
1. Open data policy
1.1 Public Information Act
(_brief intro + link to Riigi Teataja_)
1.2 Open data green paper
(_brief intro + link to file on MKM’s website_) 
2. Data publication guidelines
2.1 Metadata
2.2 Licenses
3. Events
4. FAQ
5. Contact

Also proposing to rename "Blog" into:

**EE**: Uudised ja blogi
**EN**: News & blog

**Comment by infokujur** [comment]
Looks good to me.

**Comment by otuxe** [comment]
Sobib!
