### ISSUE TITLE
Dataset preview functionality

### ISSUE THREAD

**Issue by keeganmcbride** [okestonia/jkan#21]

**Comment by keeganmcbride** [comment]
Still being investigated, seems to be only possible with CSV files, needs to be able to pull from URL.

**Comment by keeganmcbride** [comment]
For this we can use something like https://www.papaparse.com/ and https://github.com/jackfranklin/so-fetch to fetch the CSV from URL and then preview the head of the file.

**Comment by andreskytt** [comment]
A la data.sandiego.gov. Display a first x rows of a dataset if its a data dump

**Comment by andreskytt** [comment]
Use results from #100

**Comment by keeganmcbride** [comment]
> A la data.sandiego.gov. Display a first x rows of a dataset if its a data dump

The approach they used doesn't actually work for us, so something else needs to be approached. We run into issues with CORS.

**Comment by keeganmcbride** [comment]
Use http://datapipes.okfnlabs.org/ to fetch and prase CSV files
