### ISSUE TITLE
Fix dataset URLs

### ISSUE THREAD

**Issue by keeganmcbride** [okestonia/jkan#22]
Currently, most datasets (available here: https://github.com/keeganmcbride/jkan/tree/gh-pages/_datasets) are pointing to URLs on the opendata.riik.ee page. These URLs will cease to work once the OGD portal is migrated. Thus, we need to go through the list of datasets and change the URLs to their current locations (if publicly available). If no URL is available, the dataset will be downloaded and uploaded to an S3 bucket and then changed at a later date.

**Comment by andreskytt** [comment]
https://opendata.riik.ee/et/dataset/7e4e201b-4bd0-467f-98c2-abe8c130cba2/resource/19ab6ae1-2f6f-4387-9d65-cf959daba087/download/etisavaandmetekasutamineapiliidesevahendusel.pdf from eesti-teadusinfos-steem.md Would actually be better suited to be uploaded to etis.ee - its API docs

**Comment by andreskytt** [comment]
eesti-tollitariifistik_01022018.md kõik lingid

**Comment by andreskytt** [comment]
https://opendata.riik.ee/en/dataset/01939344-6e19-4236-8850-5f5478fe7135/resource/b96a2ac0-ce41-4b7c-a4b6-3d27d1769e04/download/puhasfidek2015utf8.txt in fidek2015.md

**Comment by andreskytt** [comment]
https://opendata.riik.ee/dataset/d889f5ab-e6da-4376-9c6e-25249baf2a4c/resource/15be7427-32c4-4f90-adff-b9832d1901e2/download/parameeterexcel.xlsx

https://opendata.riik.ee/dataset/d889f5ab-e6da-4376-9c6e-25249baf2a4c/resource/e08a1aa2-906f-48e0-b88e-b05b8ffd76d7/download/parameeter.csv

in sotsiaalteenuste-ja-toetuste-andmeregister-star.md

**Comment by keeganmcbride** [comment]
Created downloads folder and added in files there. This is now resolved.
