### ISSUE TITLE
Improve transliteration into SEF URLs

### ISSUE THREAD

**Issue by peepkungas** [okestonia/jkan#224]
To improve visibility of dataset description in SERP-s improve transliteration of characters such that similar letters will be used instead of dashes. E.g. instead of https://opendata.riik.ee/datasets/p-ringud-kodakondsus-ja-migratsiooni-dokumentide-kehtivuse-v-i-menetlemise-staatuse-kohta/ there should be URL https://opendata.riik.ee/datasets/paringud-kodakondsus-ja-migratsiooni-dokumentide-kehtivuse-voi-menetlemise-staatuse-kohta/

**Comment by keeganmcbride** [comment]
We will take this in mind for future datasets, but for current datasets we wish to keep the same URLs.
