### ISSUE TITLE
Add CC 4.0 licence as page linked to Lisainfo > CC 4.0 litsents

### ISSUE THREAD

**Issue by infokujur** [okestonia/jkan#226]
[CC 4.0_litsents_EN_est.docx](https://github.com/okestonia/jkan/files/2951537/CC.4.0_litsents_EN_est.docx)
[Considerations for licensors and licensees_est.docx](https://github.com/okestonia/jkan/files/2951538/Considerations.for.licensors.and.licensees_est.docx)

**Comment by puik** [comment]
[Täpsustavad küsimused jätkuvalt teises lõimes.](https://github.com/okestonia/opendata-issue-tracker/issues/94#issuecomment-471470946)

**Comment by keeganmcbride** [comment]
Will be added .

**Comment by infokujur** [comment]
@maarjatoots - this also whould go to policy area then.

**Comment by keeganmcbride** [comment]
Now included in new KKK + FAQs.
