### ISSUE TITLE
Harmonize dataset name and filename

### ISSUE THREAD

**Issue by keeganmcbride** [okestonia/jkan#298]
Since the generation of the dataset page happens based on filename rather than the name of the dataset, the ordering of the datasets is a bit weird. One proposed way to fix is to ensure that the filename accurately reflects the dataset name.

**Comment by andreskytt** [comment]
That would break the URLs, though, wouldn't it?

**Comment by keeganmcbride** [comment]
Will do for future datasets, but not for current ones. We should add info to wiki / template.

**Comment by keeganmcbride** [comment]
Filter dataset page based on dataset title rather than file name
