### ISSUE TITLE
Blog UI

### ISSUE THREAD

**Issue by keeganmcbride** [okestonia/jkan#299]
Since we now have different sorts of articles in the blog section, we need to discuss how to best display. It also needs to be debated whether or not news articles or working group descriptions belong in the blog section or somewhere else.

**Comment by keeganmcbride** [comment]
Create filter by category type (Maarja Leena to create)

**Comment by infokujur** [comment]
Category types:
Artikkel - Article
Uudis - News
Juhend - Guide
KKK - FAQ
Töödokument - Working paper

**Comment by infokujur** [comment]
Do You want to add something here? @maarjatoots
