### ISSUE TITLE
Add a note on license to the "how to contribute" wiki

### ISSUE THREAD

**Issue by andreskytt** [okestonia/jkan#308]
Add an explanation, that we will add license x unless you supply one

**Comment by andreskytt** [comment]
@infokujur Which one shall we use?

**Comment by infokujur** [comment]
According to this discussion we use CC-BY 3.0 (as it's reccommended in Green Paper) https://github.com/okestonia/jkan/issues/75#issuecomment-456700954 (Also we should keep it in mind that 4.0 is now out and we might consider that for the future.)

**Comment by andreskytt** [comment]
9933e8e5
