### ISSUE TITLE
Add organization descriptions 

### ISSUE THREAD

**Issue by keeganmcbride** [okestonia/jkan#34]
Currently, not many organizations have descriptions. These should be added for each organization.

**Comment by otuxe** [comment]
Unfortunately not, low priority, organizations should perhaps update themselves. Sending out that information on Tuesday.

**Comment by jamesherne** [comment]
This information is usually found on the organisation's webpage, so it can be copy-pasted

**Comment by jamesherne** [comment]
I will take information that is available on the websites of the organizations and will modify the files at https://github.com/okestonia/jkan/blob/master/_organizations of the organisations that have no descriptions at all. Will try to do it in both languages.

**Comment by keeganmcbride** [comment]
Hi James,

There are a large number of organizations that do not have any datasets attached to them, probably it is safer to go through https://opendata.riik.ee/teabevaldajad/ and only update organization files for those listed here. Thanks for taking the time to do this, just as a note, we will have to check with each organization individually in order to update their information and, as such, PRs may take some time to be approved. @andreskytt

**Comment by jamesherne** [comment]
https://opendata.riik.ee/et/orgs/aegviidu-vallavalitsus/ Aegviidu rural municipality doesn't exist anymore as it was merged with Anija in 2017. Should you delete it? The contact e-mail is not valid either (the domain aegviidu.ee is currently for sale at Sedo).

**Comment by keeganmcbride** [comment]
This is now up to the data provider to supply, I suppose we can close this issue now? @infokujur @andreskytt

**Comment by andreskytt** [comment]
Yes, I agree.
