### ISSUE TITLE
Remove old RIHA link

### ISSUE THREAD

**Issue by andreskytt** [okestonia/jkan#344]
Apparently there is a weird page hanging on at https://opendata.riik.ee/datasets/riha-brief/ which has different content than https://opendata.riik.ee/andmehulgad/riha-brief/ There does not seem to be a .md file associated with the URL in the repo at all. https://opendata.riik.ee/datasets/riha-brief/ should be removed.

**Comment by keeganmcbride** [comment]
Yes, this /datasets page should not be hanging out at all. Not sure where it is coming from, need to look into it as it is also using older bootstrap layouts etc which have been fixed for months now.

**Comment by keeganmcbride** [comment]
Fixed now.

**Comment by keeganmcbride** [comment]
Now fixed.
