### ISSUE TITLE
Typo on "about" page

### ISSUE THREAD

**Issue by andreskytt** [okestonia/jkan#350]
romull@taltech.ee writes in:

> in the english version of the open data portal you state that: "Freely available open government data can contribute to: - simulating the economy" (https://opendata.riik.ee/en/about/)
> 
> Do you mean simulating or stimulating?
> 

This is probably the latter. To be confirmed and, if so, fixed.

**Comment by keeganmcbride** [comment]
will fix, definitely a typo.
