### ISSUE TITLE
Missing title attribute in dataset pages

### ISSUE THREAD

**Issue by tormi** [okestonia/jkan#356]
For example: https://opendata.riik.ee/en/andmehulgad/aadressiandmed/

<img width="906" alt="Screenshot 2019-05-26 at 16 36 27" src="https://user-images.githubusercontent.com/146800/58382572-aa643900-7fd4-11e9-8b26-6d1fea2751d2.png">

**Comment by keeganmcbride** [comment]
Thanks will fix

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by keeganmcbride** [comment]
Should be fixed with most recent commit.

**Comment by tormi** [comment]
Thanks, title for `et` is fixed now. Could we use `title_en` for dataset pages in English?

**Comment by keeganmcbride** [comment]
Should be possible, I think right now this title is just pulling from the name of the file. WIll look into how to do it better.
