### ISSUE TITLE
Update GitHub project description and URL

### ISSUE THREAD

**Issue by moll** [okestonia/jkan#395]
I noticed the description and URL for this repository points to the general JKAN page. I'd say it should instead say "Estonian Open Data Portal" and link to https://opendata.riik.ee. Otherwise if you arrive at the repository without having visited the site first, you've no idea where it lives.

**Comment by keeganmcbride** [comment]
Agree, need to also deal with this also as part of https://github.com/okestonia/jkan/issues/135 . Thanks.

**Comment by moll** [comment]
:+1: 

Might want to rethink whether naming the repo itself "jkan" is a good plan forward, too. JKAN, after all, is just an implementation detail.
