### ISSUE TITLE
Lisada JUHEND Kuidas avaldada andmehulki opendata.riik.ee portaalis, mis põhinevad mõne teise organisatsiooni andmetel

### ISSUE THREAD

**Issue by infokujur** [okestonia/jkan#403]
https://docs.google.com/document/d/1RsMe4JmuFbR6OhwlFO9mkEN6jSV7d688aTVIVtSldco/edit#heading=h.mj5wmwvjn5nc

Kui lehele lisatud, siis link vaja postitada: https://github.com/okestonia/opendata-issue-tracker/issues/212

**Comment by janesmae** [comment]
Tere, 

loen seda juhendit ja sela lõpus on lause "Algandmete andja peaks vastutama ainult selle eest, et metaandmed vastavad tõele ning et avaldatud kood tõepoolest produtseerib avaldatud teisesed andmed." 

Kas terminiga "algandmete andja" mõeldakse algandmete allikat või sekundaarse andmehulga avaldajat?

**Comment by andreskytt** [comment]
Jah, tõepoolest sõnestus oli probleemne. Mõeldud on sekundaarsete andmete avaldajat. Nüüd peaks parem olema.

**Comment by janesmae** [comment]
Vabandan tähenärimise pärast aga see dokument vajaks eraldi terminite alamosa või viidet mõnele infoallikale, kus terminid on üheselt ja selgelt määratud. Lisasin dokumendile veel mõned kommentaarid rohkem tagasiside vormis.

**Comment by infokujur** [comment]
Vaatame peale.
Ja paralleelselt tegeleme materjalidega korrastamisega mingile maale #197 . Eelmisest tuli struktuur üle as is, aga maailm on vahepeal edasi arenenud st terminid on küll olemas, aga ei leita üles. Sellega tuleb tegeleda 396#issuecomment-507059389 ja kasutajaliidesele terviklikult läheneda.
