### ISSUE TITLE
Avaandmete foorumi materjalid

### ISSUE THREAD

**Issue by infokujur** [okestonia/jkan#404]
Tagasisidega saadetud kokkuvõtted:
https://drive.google.com/drive/folders/1OP-4VZc7wWh-PRzMqUGLm6S3VNywr5SU

Videod:
https://www.youtube.com/channel/UCj9cgCczo1CA727Lx49sWyA/videos

Fotod:
https://www.facebook.com/events/1132093016967875/permalink/1225347114309131/

**Comment by keeganmcbride** [comment]
Where is this supposed to go on the web page?
