### ISSUE TITLE
Add potential application - heat map of the Estonian economy

### ISSUE THREAD

**Issue by tkutsar** [okestonia/jkan#438]
Author Andres Võrk from CITIS:

http://shiny.citis.ut.ee/avork/EstonianHeatmap/

Another similar application (uses monthly data from EMTA, which is open, but currently not accesible from web):

http://shiny.citis.ut.ee/avork/Majandusekiirhinnang/

**Comment by keeganmcbride** [comment]
both added. Please provide translation of title for the first app into Estonian.

**Comment by infokujur** [comment]
Eesti majanduse termopilt.

Palun parandage, kui saab suupärasemalt :)
