### ISSUE TITLE
Add RSS feed to the blog, datasets, applications

### ISSUE THREAD

**Issue by otuxe** [okestonia/jkan#60]

**Comment by keeganmcbride** [comment]
Will integrate jekyll-feed

**Comment by keeganmcbride** [comment]
See here for an example page: https://github.com/cityofsandiego/seaboard/blob/master/src/feed.xml

**Comment by keeganmcbride** [comment]
This is here, but needs to be worked on a bit more. May need to switch from the plugin to something more custom: https://opendata.riik.ee/feed/datasets.xml

**Comment by keeganmcbride** [comment]
Jekyll-feed is working, but doesn't work so well. Should investigate improvements.

**Comment by keeganmcbride** [comment]
https://opendata.riik.ee/datasetfeed.xml
https://opendata.riik.ee/blogfeed.xml
