### ISSUE TITLE
URL semantics should follow the same rules/language/formatting

### ISSUE THREAD

**Issue by otuxe** [okestonia/jkan#62]
For instance:
http://185.174.163.43/metaandmed/
http://185.174.163.43/datasets/
http://185.174.163.43/blogi/
http://185.174.163.43/apps/

**Comment by keeganmcbride** [comment]
please provide suggested URL names

**Comment by otuxe** [comment]
As ODP will be in English as well, we can make the following changes:
https://opendata.riik.ee/blogi/    -> https://opendata.riik.ee/**blog**/
https://opendata.riik.ee/metaandmed/   ->   https://opendata.riik.ee/**metadata**/
https://opendata.riik.ee/kkk/   ->   https://opendata.riik.ee/**faq**/
https://opendata.riik.ee/kontaktid/   ->   https://opendata.riik.ee/**contacts**/

**Comment by keeganmcbride** [comment]
@otuxe , thanks, easy fix I will have this updated by tonight.

**Comment by keeganmcbride** [comment]
changed
