### ISSUE TITLE
Add more color to the blog (picture, description etc.) Make it more similar to the applications page

### ISSUE THREAD

**Issue by otuxe** [okestonia/jkan#63]

**Comment by keeganmcbride** [comment]
Can you give some examples on what you're expecting?

**Comment by otuxe** [comment]
We should make the blog section similar to the applications section (https://opendata.riik.ee/apps/). Title, picture and small introduction.

**Comment by andreskytt** [comment]
- Re-arrange as a grid as the application page
- @infokujur will assign photos
- Have the photos hosted at the portal and also loaded from there
