### ISSUE TITLE
Make "contact us" more personal, add "Ott Velsberg" and "Maarja-Leena Saar". Add pictures.

### ISSUE THREAD

**Issue by otuxe** [okestonia/jkan#64]

**Comment by keeganmcbride** [comment]
Plz link pictures and I can update.

**Comment by keeganmcbride** [comment]
@infokujur can you please provide text/suggestions?

**Comment by infokujur** [comment]
![img_0233_smaller](https://user-images.githubusercontent.com/12999094/47966165-117dc880-e058-11e8-9297-937dcbb14504.png)
Title - „Avaandmete kasutamise edendamine ” projekti juht, e-post: maarjaleena@okee.ee

**Comment by infokujur** [comment]
@otuxe - please add Your picture also.

**Comment by otuxe** [comment]
Title - Eesti riigi Chief Data Officer, e-post: ott.velsberg@mkm.ee<mailto:ott.velsberg@mkm.ee>
[cid:78494512-928A-4C36-8AE3-EA53E9A02DBF@zyxel.localhost]


Lugupidamisega/Kind regards,
Ott Velsberg

Chief Data Officer
Ministry of Economic Affairs and Communications
Republic of Estonia

ott.velsberg@mkm.ee<mailto:ott.velsberg@mkm.ee>
Phone: +372 51 33 898
Skype: ott.velsberg
twitter @ottvelsberg

**Comment by keeganmcbride** [comment]
@otuxe Can you send me this via email or comment/upload directly to the issue?

**Comment by otuxe** [comment]
Title - Eesti riigi Chief Data Officer, e-post: ott.velsberg@mkm.ee

![ott](https://user-images.githubusercontent.com/26219801/48413978-090d4800-e752-11e8-96d1-ff5f74f2ede9.jpg)

**Comment by keeganmcbride** [comment]
fixed
