### ISSUE TITLE
Change date structure for the blog posts to dd/mm/yyyy

### ISSUE THREAD

**Issue by otuxe** [okestonia/jkan#80]
https://opendata.riik.ee/blogi/ 

Currently : Maarja Toots 2018/06/12  change to dd/mm/yyyy

**Comment by keeganmcbride** [comment]
Dates are like this to comply with xsd:date, but I don't see any reason why we can't change this. @andreskytt do you see any issues?

**Comment by keeganmcbride** [comment]
done
