### ISSUE TITLE
Fix Translation for organization.html and dataset.html

### ISSUE THREAD

**Issue by keeganmcbride** [okestonia/jkan#87]
This seems to be a JS issue, to be investigated.

**Comment by keeganmcbride** [comment]
Dataset.html and organization.html need to be able to pick up the page.lang and display information in correct language. ATM when going to an individual dataset or organization, the menu will automatically change to English due to a logic issue and it is not possible to display the English dataset pages (see, for example https://opendata.riik.ee/en/datasets/aadressiandmed/)

**Comment by infokujur** [comment]
Translated and edited datasets refered in this issue: https://github.com/okestonia/jkan/issues/140
