### ISSUE TITLE
Add link to Github issue tracker to front page

### ISSUE THREAD

**Issue by maarjatoots** [okestonia/jkan#89]
... or under the Andmehulgad/Datasets section, whichever makes more sense. In any case, opportunities for discussion & feedback should be made visible and easily findable on the portal.

**Comment by keeganmcbride** [comment]
There is a link on the datasets page atm, that is where @otuxe wanted it.

**Comment by keeganmcbride** [comment]
![image](https://user-images.githubusercontent.com/20890951/48888586-e22ed000-ee3b-11e8-8928-f3143da30f7b.png)
