### ISSUE TITLE
opendata.riik.ee brauser cache

### ISSUE THREAD

**Issue by jtali** [okestonia/jkan#92]
Brauser cache will cause problems after merge.
For disable browsers cache please use tags : 

`<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="0" />`

**Comment by keeganmcbride** [comment]
Changes made to server config, this should be resolved now.
