### ISSUE TITLE
Creation and modification dates are misleading and confused with applying to dataset 

### ISSUE THREAD

**Issue by moll** [okestonia/jkan#93]
Hey,

Noticed every page display the page's last modified date ("Viimati muudetud (YYYY-MM-DD)"). I know of at least one other person that was misled to thinking it was the last-modified date of the dataset, not of the webpage itself. I'd say this should be clarified and/or de-emphasized. Who's it for anyway?

**Comment by keeganmcbride** [comment]
Hi @moll, the last modified and date created are part of DCAT-AP specification and required metadata for open data, see, for example: https://theodi.org/article/marking-up-your-dataset-with-dcat/ or https://www.w3.org/TR/vocab-dcat/ . The previous open government data portal was a CKAN based solution and should have been harvesting this information automatically, however this feature was never used and the last modified and date created dates reflected only when the datasets were uploaded to the portal. When we switched to the new solution based on JKAN, we scraped the old datasets and part of this information was the date_modified/date_created information. 

Ideally, the date created and date modified should be updated by the data service provider whenever the dataset is changed on the portal, for a good example see @jtali 's work here: https://github.com/okestonia/jkan/pull/90 Of course, what we have right now is a front end only solution, so if the dataset at the provided URL has been modified recently, this will not be picked up automatiaclly; this was the case with the last open data portal as well. That being said, @andreskytt and I have discussed a bit on how to improve this situation and are thinking about writing some sort of script that will compare file hashes and then update if changes are detected, but this is still in quite early stage. 

If there is particular datasets that you are working with right now and would like to update this information, please let me know and I can do this straight away, or you may also update via a PR.

**Comment by keeganmcbride** [comment]
After also talking with the European Data Portal it seems the best option is to hide the last_modified date now to avoid confusion while we work on a better fix.

**Comment by moll** [comment]
Wouldn't the simplest shell script that gets the Last-Modified date after a `HEAD` request be sufficient in place of a task runner with GUIs and whatnots that is https://github.com/apache/incubator-airflow?

**Comment by keeganmcbride** [comment]
@moll we had a meeting at MKM today and @andreskytt and I discussed this a bit as well. We will be using some scripts and hopefully have a solution for more accurate last-modified information soon.

**Comment by keeganmcbride** [comment]
https://github.com/okestonia/jkan/issues/101 https://github.com/okestonia/jkan/issues/100

**Comment by keeganmcbride** [comment]
Hi @moll , we now have a script running in the background that will check for updates and automatically update the date_changed if it is detected. See https://github.com/okestonia/jkan/blob/ce35ae8c04ed56609079c518bdf83adde7aecc75/datachanges.json and https://github.com/okestonia/jkan/blob/master/checkUpdates.py
